# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# CS 558 Network Security Blog
title: Network Security News
email: asambors@bu.edu
description: > # this means to ignore newlines until "baseurl:"
  CS558 Network Security is taught by Professor Sharon Goldberg
  at Boston University. This is a course blog for the Spring 2017
  where students post their research on recent network security 
  hacks and vulnerabilities.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://asamborski.github.io/cs558_s17_blog" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  asamborski

# Links
piazza_link: https://piazza.com/class/iwxvspg1o217ed
github_link: https://github.com/asamborski/cs558_s17_blog#cs-558-network-security

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
